---
# tasks file for ansible-role-ohmyzsh
- name: Check for oh-my-zsh
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzsh
- name: Install oh-my-zsh
  shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended'
  when: not ohmyzsh.stat.exists
- name: Ensure ZSH_CUSTOM Directories Exist
  file:
    state: directory
    path: "{{ loop_var_custom_path }}"
    owner: "{{ ansible_user }}"
    mode: 0755
  with_items:
    - "{{ ohmyzsh_custom_path }}/plugins"
    - "{{ ohmyzsh_custom_path }}/themes"
  loop_control:
    loop_var: "loop_var_custom_path"
- name: Get Custom Plugins
  git:
    repo: "{{ loop_var_custom_plugin.repo }}"
    dest: "{{ ohmyzsh_custom_path }}/plugins/{{ loop_var_custom_plugin.dest }}"
    update: yes
  with_items: "{{ ohmyzsh_custom_plugins }}"
  loop_control:
    loop_var: "loop_var_custom_plugin"
- name: Get Custom Themes
  git:
    repo: "{{ loop_var_custom_theme.repo }}"
    dest: "{{ ohmyzsh_custom_path }}/themes/{{ loop_var_custom_theme.dest }}"
    update: yes
  with_items: "{{ ohmyzsh_custom_themes }}"
  loop_control:
    loop_var: "loop_var_custom_theme"
- name: Link Custom Themes
  file:
    state: link
    src: "{{ ohmyzsh_custom_path }}/themes/{{ loop_var_custom_theme.0.dest }}/{{ loop_var_custom_theme.1 }}"
    dest: "{{ ohmyzsh_custom_path }}/themes/{{ loop_var_custom_theme.1 }}"
  with_subelements:
    - "{{ ohmyzsh_custom_themes }}"
    - theme_names
  loop_control:
    loop_var: "loop_var_custom_theme"
- name: Generate PATH export statement
  set_fact:
    ohmyzsh_generated_path: |-
      {% set p = ohmyzsh_generated_path %}
      {% set p = loop_var_path_export + ':' + p %}
      {{ p }}
  with_items: "{{ ohmyzsh_path_exports }}"
  loop_control:
    loop_var: "loop_var_path_export"
- name: Deploy ohmyzsh Configuration
  template:
    src: "zshrc.j2"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ ansible_user }}"
    mode: 0644
- name: Cutomize Plugins
  lineinfile: "{{ item.value }}"
  with_dict:
    - "{{ ohmyzsh_plugin_customizations }}"
